# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Fresh4Less - Keeping fresh so you don't have to
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Fresh games and they're done dirt cheap
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: fresh4less
github_username:  fresh4less

permalink: /:categories/:title

# Build settings
markdown: kramdown
encoding: utf-8
source: build
destination: dist
